(() => {
  "use strict";
  const DAY=86400000;
  const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
  const energy=m=>{const f=Number(m?.fatigueBefore);return f>=1&&f<=5?6-f:null};
  const pct=(a,b)=>Math.round(a/Math.max(1,b)*100);
  const confidence=(a,b,effect)=>Math.max(0,Math.min(.96,.25+Math.min(a,b)/30+Math.abs(effect)/3));
  const stage=c=>c>=.82?{id:"confirmed",label:"Je sais",icon:"💡"}:c>=.64?{id:"observing",label:"Je pense",icon:"🔎"}:{id:"discovering",label:"Je découvre",icon:"🌱"};
  const mk=(x)=>({...x,confidence:confidence(x.exposed,x.comparison,x.effect),stage:stage(confidence(x.exposed,x.comparison,x.effect))});
  function days(db,lookback=180){const cutoff=Date.now()-lookback*DAY;return Object.entries(db?.days||{}).map(([date,d])=>({...d,date,meals:Array.isArray(d.meals)?d.meals:[]})).filter(d=>new Date(d.date+"T12:00:00").getTime()>=cutoff).sort((a,b)=>a.date.localeCompare(b.date));}
  function dayEnergy(d){return mean(d.meals.map(energy).filter(Number.isFinite));}
  function compare(list,test,labelA,labelB,min=6){const a=list.filter(test).map(dayEnergy).filter(Number.isFinite),b=list.filter(x=>!test(x)).map(dayEnergy).filter(Number.isFinite);if(a.length<min||b.length<min)return null;const av=mean(a),bv=mean(b),effect=av-bv;if(Math.abs(effect)<.35)return null;return{a,b,av,bv,effect,labelA,labelB};}
  function sleepInsight(list){const eligible=list.filter(d=>Number.isFinite(Number(d.sleepHours)));const c=compare(eligible,d=>Number(d.sleepHours)>=7,"7 h ou plus","moins de 7 h");if(!c)return null;return mk({id:"sleep-energy",category:"Sommeil",icon:"🛌",title:c.effect>0?"Un sommeil plus long accompagne souvent une meilleure énergie":"La durée du sommeil semble liée à ton énergie",text:c.effect>0?"Les journées suivant au moins 7 heures de sommeil montrent généralement une énergie plus élevée.":"Une différence d’énergie revient selon la durée de ton sommeil.",exposed:c.a.length,comparison:c.b.length,effect:c.effect,evidence:[`${c.a.length} journées avec ${c.labelA}`,`${c.b.length} journées avec ${c.labelB}`,`Énergie moyenne : ${c.av.toFixed(1)} contre ${c.bv.toFixed(1)}`],disclaimer:"Cette association ne prouve pas qu’une durée de sommeil cause directement la différence."});}
  function hydrationInsight(list,goal=8){const eligible=list.filter(d=>Number.isFinite(Number(d.water)));const threshold=Math.max(4,Math.round(Number(goal)||8));const c=compare(eligible,d=>Number(d.water)>=threshold,`${threshold} verres ou plus`,`${threshold-1} verres ou moins`);if(!c)return null;return mk({id:"water-energy",category:"Hydratation",icon:"💧",title:c.effect>0?"Une meilleure hydratation accompagne souvent une meilleure énergie":"Ton hydratation et ton énergie semblent varier ensemble",text:`Les journées avec au moins ${threshold} verres présentent une différence répétée d’énergie.`,exposed:c.a.length,comparison:c.b.length,effect:c.effect,evidence:[`${c.a.length} journées à ${threshold} verres ou plus`,`${c.b.length} journées sous ce niveau`,`Énergie moyenne : ${c.av.toFixed(1)} contre ${c.bv.toFixed(1)}`],disclaimer:"D’autres facteurs peuvent expliquer une partie de cette différence."});}
  function breakfastInsight(list){const eligible=list.filter(d=>d.meals.some(m=>Number.isFinite(energy(m))));const c=compare(eligible,d=>d.meals.some(m=>m.type==="Déjeuner"),"avec déjeuner","sans déjeuner");if(!c)return null;return mk({id:"breakfast-energy",category:"Habitudes",icon:"🥣",title:c.effect>0?"Déjeuner semble accompagner une énergie plus stable":"Tes journées diffèrent selon la présence d’un déjeuner",text:"Le niveau d’énergie enregistré varie entre les journées avec et sans déjeuner.",exposed:c.a.length,comparison:c.b.length,effect:c.effect,evidence:[`${c.a.length} journées avec déjeuner`,`${c.b.length} journées sans déjeuner`,`Énergie moyenne : ${c.av.toFixed(1)} contre ${c.bv.toFixed(1)}`],disclaimer:"Cette comparaison ne tient pas compte de toutes les différences entre les journées."});}
  const symptomAliases={
    headache:["headache","maux de tête","mal de tête"],
    stomachache:["stomachache","maux de ventre","mal de ventre"],
    bloating:["bloating","ballonnements","ballonnement"],
    nausea:["nausea","nausées","nausée"],
    reflux:["reflux"],
    gas:["gas","gaz"]
  };
  const scoreMap=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
  const symptomScore=(scores,tag)=>{for(const alias of symptomAliases[tag]){const value=Number(scores?.[alias]);if(value>=1&&value<=5)return value}return 0};
  const symptomChange=(meal,tag)=>{if(!meal?.feeling)return 0;const after=scoreMap(meal.feeling.scores),before=scoreMap(meal.feelingsBefore||meal.feeling.beforeScores);if(Object.keys(after).length)return symptomScore(after,tag)-symptomScore(before,tag);return (meal.feeling.tags||[]).some(value=>symptomAliases[tag].includes(String(value).toLowerCase()))?(Number(meal.feeling.rating)||3):0};
  const hasSymptom=(meal,tag)=>symptomChange(meal,tag)>0;
  function symptomInsights(list){const labels={headache:"maux de tête",stomachache:"maux de ventre",bloating:"ballonnements",nausea:"nausées",reflux:"reflux",gas:"gaz"};const families=[{id:"dairy",label:"produits laitiers",re:/\b(lait|milk|fromage|cheese|yogourt|yogurt|cr[eè]me|cream|lactose|whey)\b/i},{id:"legume",label:"légumineuses",re:/\b(pois chiche|chickpea|lentille|lentil|haricot|bean|tofu|edamame)\b/i},{id:"high-fiber",label:"aliments riches en fibres",re:/\b(avoine|oat|chia|lin|flax|lentille|haricot|pois chiche|brocoli|pomme|apple|poire|pear)\b/i}];const meals=list.flatMap(d=>d.meals).filter(m=>m?.feeling?.tags?.length);const out=[];for(const [tag,label] of Object.entries(labels)){const tagged=meals.filter(m=>hasSymptom(m,tag));if(tagged.length<5)continue;for(const f of families){const exposed=tagged.filter(m=>f.re.test(`${m.description||""} ${m.notes||""}`)).length;const allExposed=meals.filter(m=>f.re.test(`${m.description||""} ${m.notes||""}`)).length;const allOther=meals.length-allExposed,tagOther=tagged.length-exposed;if(exposed<4||allExposed<6||allOther<6)continue;const rateA=exposed/allExposed,rateB=tagOther/allOther,effect=rateA-rateB;if(effect<.18)continue;out.push(mk({id:`symptom-${tag}-${f.id}`,category:"Symptômes",icon:"🤕",title:`Une association possible apparaît entre ${f.label} et ${label}`,text:`${label.charAt(0).toUpperCase()+label.slice(1)} sont notés plus souvent après les repas où ${f.label} sont présents.`,exposed:allExposed,comparison:allOther,effect:effect*2,evidence:[`${exposed} ressentis concernés parmi ${allExposed} repas exposés`,`${tagOther} parmi ${allOther} autres repas`,`Fréquence observée : ${pct(exposed,allExposed)} % contre ${pct(tagOther,allOther)} %`],disclaimer:"Il s’agit d’une association dans le journal, pas d’un diagnostic ni d’une preuve d’intolérance."}));}}
    return out;
  }
  function analyze(db,options={}){const list=days(db,options.lookbackDays||180);const insights=symptomInsights(list).filter(Boolean).sort((a,b)=>b.confidence-a.confidence).slice(0,6);return{version:2,generatedAt:new Date().toISOString(),analyzedDays:list.length,insights};}
  window.EnergieInsightEngine=Object.freeze({version:1,analyze});
})();
