(() => {
"use strict";
const CFG=window.ENERGIE_CONFIG||{};
const APP_KEY="energieRepasDB";
const BACKUP_KEY="energieRepasBackups";
const OUTBOX_KEY="energieRepasOutboxV13";
const CURRENT_VERSION=4;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const todayKey=()=>new Date().toLocaleDateString("en-CA");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const client=(window.supabase&&CFG.supabaseUrl&&CFG.supabasePublishableKey)?window.supabase.createClient(CFG.supabaseUrl,CFG.supabasePublishableKey):null;
let session=null, currentView="today", selectedDate=todayKey(), syncState="local", photoData=null, photoRemoved=false;

function freshDB(){return{version:CURRENT_VERSION,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{waterGoal:8,theme:"system"},days:{}}}
function ensureDay(db,key=todayKey()){if(!db.days[key])db.days[key]={date:key,sleepHours:null,water:0,activities:[],meals:[],updatedAt:new Date().toISOString()};const d=db.days[key];d.activities=Array.isArray(d.activities)?d.activities:[];d.meals=Array.isArray(d.meals)?d.meals:[];d.water=Number(d.water)||0;return d}
function normalMeal(m={},date=todayKey()){return{id:m.id||uid(),date:m.date||date,time:m.time||"12:00",type:m.type||m.mealType||m.typeRepas||"Repas",description:m.description||m.food||m.aliments||m.repas||m.details||"",fatigueBefore:clamp(m.fatigueBefore??m.fatigueAvant??m.before,0,5),fatigueAfter:clamp(m.fatigueAfter??m.fatigueApres??m.after??m.fatigue1h??m.after1h,0,5),notes:m.notes||"",photoUrl:m.photoUrl||null,photoPath:m.photoPath||null,photoLocal:m.photoLocal||m.photo||m.image||null,createdAt:m.createdAt||new Date().toISOString(),updatedAt:m.updatedAt||new Date().toISOString()}}
function migrate(raw){const out=freshDB();if(!raw||typeof raw!=="object")return out;out.settings={...out.settings,...(raw.settings||{})};if(raw.days&&typeof raw.days==="object"){Object.entries(raw.days).forEach(([k,d])=>{const day=ensureDay(out,k);day.sleepHours=d.sleepHours??d.sleep??d.sommeil??null;day.water=Number(d.water??d.waterGlasses??d.eau??0)||0;day.activities=Array.isArray(d.activities)?d.activities:[];day.meals=(d.meals||d.repas||[]).map(m=>normalMeal(m,k));day.updatedAt=d.updatedAt||new Date().toISOString()});return out}const arr=[raw.meals,raw.repas,raw.entries,raw.history,raw.logs,Array.isArray(raw)?raw:null].find(Array.isArray);if(arr)arr.forEach(x=>{const m=normalMeal(x,x.date||x.day||todayKey());ensureDay(out,m.date).meals.push(m)});return out}
function backup(payload,reason){try{const b=JSON.parse(localStorage.getItem(BACKUP_KEY)||"[]");b.unshift({at:new Date().toISOString(),reason,payload});localStorage.setItem(BACKUP_KEY,JSON.stringify(b.slice(0,20)))}catch(e){console.warn(e)}}
function load(){const raw=localStorage.getItem(APP_KEY);if(!raw)return freshDB();try{const parsed=JSON.parse(raw);backup(parsed,"ouverture-v1.3");return migrate(parsed)}catch(e){backup(raw,"copie-illisible-v1.3");return freshDB()}}
let db=load();
function saveLocal(reason="local"){db.updatedAt=new Date().toISOString();const before=localStorage.getItem(APP_KEY);if(before){try{backup(JSON.parse(before),`avant-${reason}`)}catch(_){}}const txt=JSON.stringify(db);localStorage.setItem(APP_KEY,txt);localStorage.setItem(`${APP_KEY}_shadow`,txt)}
function outbox(){try{return JSON.parse(localStorage.getItem(OUTBOX_KEY)||"[]")}catch(_){return[]}}
function setOutbox(items){localStorage.setItem(OUTBOX_KEY,JSON.stringify(items));updateSyncBadge()}
function enqueue(op){const items=outbox();const key=`${op.kind}:${op.id||op.date}`;const idx=items.findIndex(x=>`${x.kind}:${x.id||x.date}`===key);if(idx>=0)items[idx]=op;else items.push(op);setOutbox(items);syncState="pending";updateSyncBadge();if(session&&navigator.onLine)syncNow()}
function updateSyncBadge(){const el=$("#syncBadge");if(!el)return;const pending=outbox().length;el.className="sync-badge";if(!session){el.textContent=navigator.onLine?"Non connecté":"Hors ligne";if(!navigator.onLine)el.classList.add("pending");return}if(syncState==="error"){el.textContent="Erreur synchro";el.classList.add("error")}else if(pending){el.textContent=`${pending} à synchroniser`;el.classList.add("pending")}else{el.textContent="Sauvegardé ☁️";el.classList.add("online")}}
function setDayChanged(date){const d=ensureDay(db,date);d.updatedAt=new Date().toISOString();saveLocal("jour");enqueue({kind:"day",date})}
function setMealChanged(meal){saveLocal("repas");enqueue({kind:"meal",id:meal.id,date:meal.date})}
function deleteMealLocal(meal){const d=ensureDay(db,meal.date);d.meals=d.meals.filter(x=>x.id!==meal.id);saveLocal("suppression-repas");enqueue({kind:"deleteMeal",id:meal.id,date:meal.date,photoPath:meal.photoPath})}

async function uploadPhoto(meal){if(!client||!session||!meal.photoLocal||meal.photoLocal===meal.photoUrl)return meal;const blob=await (await fetch(meal.photoLocal)).blob();const ext=(blob.type.split("/")[1]||"jpg").replace("jpeg","jpg");const path=`${session.user.id}/${meal.id}.${ext}`;const {error}=await client.storage.from("meal-photos").upload(path,blob,{upsert:true,contentType:blob.type||"image/jpeg"});if(error)throw error;meal.photoPath=path;meal.photoLocal=null;return meal}
async function signedPhoto(path){if(!path||!client)return null;const {data,error}=await client.storage.from("meal-photos").createSignedUrl(path,60*60);return error?null:data.signedUrl}
async function syncNow(){if(!client||!session||!navigator.onLine)return;syncState="syncing";updateSyncBadge();let items=outbox();const remaining=[];for(const op of items){try{if(op.kind==="day"){const d=ensureDay(db,op.date);const {error}=await client.from("daily_logs").upsert({user_id:session.user.id,log_date:op.date,sleep_hours:d.sleepHours,water:d.water,activities:d.activities,updated_at:d.updatedAt},{onConflict:"user_id,log_date"});if(error)throw error}else if(op.kind==="meal"){const d=ensureDay(db,op.date);const meal=d.meals.find(m=>m.id===op.id);if(!meal)continue;await uploadPhoto(meal);meal.updatedAt=new Date().toISOString();const {error}=await client.from("meals").upsert({id:meal.id,user_id:session.user.id,meal_date:meal.date,meal_time:meal.time,meal_type:meal.type,description:meal.description,fatigue_before:meal.fatigueBefore,fatigue_after:meal.fatigueAfter,notes:meal.notes||null,photo_path:meal.photoPath||null,created_at:meal.createdAt,updated_at:meal.updatedAt});if(error)throw error;saveLocal("photo-cloud")}else if(op.kind==="deleteMeal"){const {error}=await client.from("meals").delete().eq("id",op.id);if(error)throw error;if(op.photoPath)await client.storage.from("meal-photos").remove([op.photoPath])}}catch(e){console.error("sync",e);remaining.push(op)}}setOutbox(remaining);syncState=remaining.length?"error":"online";updateSyncBadge();if(!remaining.length)await pullCloud(false)}
async function pullCloud(show=true){if(!client||!session||!navigator.onLine)return;if(show){syncState="syncing";const el=$("#syncBadge");if(el)el.textContent="Synchronisation…"}const [{data:days,error:de},{data:meals,error:me}]=await Promise.all([client.from("daily_logs").select("*").order("log_date"),client.from("meals").select("*").order("meal_date").order("meal_time")]);if(de||me){syncState="error";updateSyncBadge();return}for(const r of days||[]){const local=ensureDay(db,r.log_date);if(!local.updatedAt||new Date(r.updated_at)>=new Date(local.updatedAt)){local.sleepHours=r.sleep_hours;local.water=r.water||0;local.activities=r.activities||[];local.updatedAt=r.updated_at}}for(const r of meals||[]){const d=ensureDay(db,r.meal_date);const remote=normalMeal({id:r.id,date:r.meal_date,time:(r.meal_time||"").slice(0,5),type:r.meal_type,description:r.description,fatigueBefore:r.fatigue_before,fatigueAfter:r.fatigue_after,notes:r.notes,photoPath:r.photo_path,createdAt:r.created_at,updatedAt:r.updated_at},r.meal_date);const i=d.meals.findIndex(x=>x.id===remote.id);if(i<0)d.meals.push(remote);else if(new Date(remote.updatedAt)>=new Date(d.meals[i].updatedAt||0))d.meals[i]={...d.meals[i],...remote}}saveLocal("retour-cloud");syncState="online";updateSyncBadge();render()}
async function seedCloudFromLocal(){if(!session)return;const ops=[];Object.entries(db.days).forEach(([date,d])=>{ops.push({kind:"day",date});d.meals.forEach(m=>ops.push({kind:"meal",id:m.id,date}))});setOutbox(ops);await syncNow()}

function mealIcon(t){return({"Déjeuner":"🍳","Dîner":"🥗","Souper":"🍲","Collation":"🍎","Boisson":"🥤"})[t]||"🍽️"}
function formatDate(k){return new Intl.DateTimeFormat("fr-CA",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${k}T12:00:00`))}
function average(arr){const x=arr.filter(n=>Number.isFinite(Number(n))&&Number(n)>0).map(Number);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null}
function render(){document.documentElement.dataset.theme=db.settings.theme==="dark"?"dark":"";$("#todayLabel").textContent=formatDate(todayKey());$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));updateSyncBadge();({today:renderToday,history:renderHistory,insights:renderInsights,profile:renderProfile}[currentView]||renderToday)()}
function renderToday(){const d=ensureDay(db,selectedDate);const goal=db.settings.waterGoal||8;const water=Array.from({length:goal},(_,i)=>`<button class="drop ${i<d.water?'filled':''}" data-water="${i+1}" aria-label="${i+1} verres">💧</button>`).join("");const meals=[...d.meals].sort((a,b)=>a.time.localeCompare(b.time));const avgAfter=average(meals.map(m=>m.fatigueAfter));$("#app").innerHTML=`${!navigator.onLine?'<div class="offline-banner">Tu es hors ligne. Les changements restent sur cet appareil et seront envoyés au retour d’Internet.</div>':''}<section class="hero"><div class="row"><div><p class="eyebrow">Aujourd'hui</p><h2>${meals.length?`Déjà ${meals.length} repas noté${meals.length>1?'s':''}`:'Une petite note à la fois'}</h2><p>${session?'Tes données sont reliées à ton compte.':'Connecte-toi pour sauvegarder dans le nuage.'}</p></div><div class="mascot">${meals.length?'🌿':'🍐'}</div></div></section><div class="grid"><section class="card"><span>😴</span><h3>Sommeil</h3><div class="metric">${d.sleepHours??'—'}${d.sleepHours!=null?' h':''}</div><button class="secondary small edit-day">Mettre à jour</button></section><section class="card"><span>⚡</span><h3>Fatigue après</h3><div class="metric">${avgAfter==null?'—':avgAfter.toFixed(1)+'/5'}</div><span class="muted small">Moyenne du jour</span></section><section class="card wide"><div class="row"><div><span>💧</span><h3>Hydratation</h3></div><strong>${d.water}/${goal}</strong></div><div class="water-row">${water}</div><span class="muted small">Touche une goutte pour choisir ton total.</span></section></div><div class="section-title"><h2>Mes repas</h2><button class="primary add-meal">＋ Ajouter</button></div><div class="stack">${meals.length?meals.map(mealCard).join(''):`<section class="card empty"><div class="food-art">🥣</div><h3>Aucun repas pour l'instant</h3><p class="muted">Une description, deux niveaux de fatigue et c'est fait.</p><button class="primary add-meal">Ajouter mon premier repas</button></section>`}</div>`;bindCommon()}
function mealCard(m){const src=m.photoUrl||m.photoLocal;return `<article class="card meal-card" data-meal="${m.id}">${src?`<img class="meal-thumb" src="${esc(src)}" alt="Photo du repas">`:`<div class="meal-thumb">${mealIcon(m.type)}</div>`}<div><h3>${esc(m.type)} · ${esc(m.time)}</h3><div class="meal-meta">${esc(m.description)}</div><div class="chips"><span class="chip">Avant ${m.fatigueBefore||'—'}/5</span><span class="chip">Après ${m.fatigueAfter||'—'}/5</span></div></div><button class="delete-meal" data-delete="${m.id}" aria-label="Supprimer">⋯</button></article>`}
function bindCommon(){$$('.add-meal').forEach(b=>b.onclick=()=>openMeal());$$('.edit-day').forEach(b=>b.onclick=openDay);$$('[data-water]').forEach(b=>b.onclick=()=>{const d=ensureDay(db,selectedDate),n=Number(b.dataset.water);d.water=(d.water===n?Math.max(0,n-1):n);setDayChanged(selectedDate);render()});$$('[data-meal]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-delete]'))return;openMeal(c.dataset.meal)});$$('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();const d=ensureDay(db,selectedDate),m=d.meals.find(x=>x.id===b.dataset.delete);if(m&&confirm('Supprimer ce repas?')){deleteMealLocal(m);render()}});hydratePhotoUrls()}
async function hydratePhotoUrls(){if(!session)return;let changed=false;for(const d of Object.values(db.days))for(const m of d.meals)if(m.photoPath&&!m.photoUrl){m.photoUrl=await signedPhoto(m.photoPath);changed=changed||!!m.photoUrl}if(changed){saveLocal('liens-photo');if(currentView==='today')render()}}
function renderHistory(){const days=Object.values(db.days).filter(d=>d.meals.length||d.water||d.sleepHours!=null).sort((a,b)=>b.date.localeCompare(a.date));$("#app").innerHTML=`<section class="hero"><p class="eyebrow">Historique</p><h2>Ton journal, sans surcharge</h2><p>Chaque journée reste modifiable.</p></section><div class="stack">${days.length?days.map(d=>`<article class="card history-day" data-date="${d.date}"><div class="row"><div><h3>${esc(formatDate(d.date))}</h3><div class="mini-stats"><span>🍽️ ${d.meals.length}</span><span>💧 ${d.water}</span><span>😴 ${d.sleepHours??'—'} h</span></div></div><span>›</span></div></article>`).join(''):`<section class="card empty"><div class="food-art">📖</div><p>Aucune journée enregistrée.</p></section>`}</div>`;$$('[data-date]').forEach(x=>x.onclick=()=>{selectedDate=x.dataset.date;currentView='today';render()})}
function renderInsights(){const meals=Object.values(db.days).flatMap(d=>d.meals);const before=average(meals.map(m=>m.fatigueBefore)),after=average(meals.map(m=>m.fatigueAfter));const delta=(before!=null&&after!=null)?after-before:null;const days=Object.values(db.days).filter(d=>d.meals.length).slice(-14);const bars=days.map(d=>{const a=average(d.meals.map(m=>m.fatigueAfter))||0;return `<i style="height:${Math.max(8,a/5*100)}%" title="${esc(d.date)} : ${a.toFixed(1)}"></i>`}).join('');$("#app").innerHTML=`<section class="hero"><p class="eyebrow">Tendances</p><h2>Des indices, pas des diagnostics</h2><p>Les tendances deviennent plus utiles à mesure que tu notes tes repas.</p></section><div class="grid"><section class="card"><h3>Fatigue avant</h3><div class="metric">${before==null?'—':before.toFixed(1)+'/5'}</div></section><section class="card"><h3>Fatigue après</h3><div class="metric">${after==null?'—':after.toFixed(1)+'/5'}</div></section><section class="card wide"><h3>Variation moyenne</h3><div class="metric">${delta==null?'—':`${delta>0?'+':''}${delta.toFixed(1)}`}</div><p class="muted small">Une valeur négative signifie moins de fatigue après les repas.</p></section><section class="card wide"><h3>Fatigue après — 14 jours</h3><div class="spark">${bars||'<span class="muted">Pas encore assez de données.</span>'}</div></section></div>`}
function renderProfile(){const backups=(()=>{try{return JSON.parse(localStorage.getItem(BACKUP_KEY)||'[]').length}catch(_){return 0}})();$("#app").innerHTML=`<section class="hero"><p class="eyebrow">Profil</p><h2>${session?esc(session.user.email):'Protège ton historique'}</h2><p>${session?'La synchronisation Supabase est active.':'La copie locale seule peut disparaître sur iPhone.'}</p></section><div class="stack"><section class="card">${session?`<div class="settings-row"><div><h3>Compte connecté</h3><p class="muted small">${esc(session.user.email)}</p></div><button class="secondary" id="syncNow">Synchroniser</button></div><button class="danger" id="signOut">Se déconnecter</button>`:`<h3>Sauvegarde en ligne</h3><p class="muted">Connecte-toi par courriel afin que les repas soient enregistrés dans Supabase.</p><button class="primary" id="signIn">Se connecter</button>`}</section><section class="card"><div class="settings-row"><div><h3>Objectif d'eau</h3><p class="muted small">Nombre de gouttes affichées</p></div><input id="waterGoal" type="number" min="1" max="20" value="${db.settings.waterGoal||8}" style="width:80px"></div></section><section class="card"><h3>Sauvegarde supplémentaire</h3><p class="muted small">${backups} copie(s) locale(s) de sécurité. L'export JSON reste une bonne copie externe.</p><div class="dialog-actions"><button class="secondary" id="exportData">Exporter JSON</button><button class="secondary" id="importData">Importer JSON</button></div></section><section class="card"><p class="muted small">Énergie & Repas V${esc(CFG.appVersion||'1.3.0')}</p></section></div>`;$("#signIn")?.addEventListener('click',()=>$("#authDialog").showModal());$("#syncNow")?.addEventListener('click',async()=>{await syncNow();await pullCloud();});$("#signOut")?.addEventListener('click',async()=>{await client.auth.signOut();session=null;render()});$("#waterGoal").onchange=e=>{db.settings.waterGoal=clamp(e.target.value,1,20);saveLocal('objectif-eau');render()};$("#exportData").onclick=exportData;$("#importData").onclick=()=>$("#importFile").click()}
function makeRatings(containerId,value){const c=$(containerId);c.innerHTML=Array.from({length:5},(_,i)=>`<button type="button" class="rating-button ${i+1===value?'active':''}" data-rating="${i+1}">${i+1}</button>`).join('');c.dataset.value=value;$$(`${containerId} [data-rating]`).forEach(b=>b.onclick=()=>{c.dataset.value=b.dataset.rating;$$(`${containerId} [data-rating]`).forEach(x=>x.classList.toggle('active',x===b))})}
function openMeal(id=null){const d=ensureDay(db,selectedDate);const m=id?d.meals.find(x=>x.id===id):null;$("#mealDialogTitle").textContent=m?'Modifier le repas':'Ajouter un repas';$("#mealId").value=m?.id||'';$("#mealType").value=m?.type||'Déjeuner';$("#mealTime").value=m?.time||new Date().toTimeString().slice(0,5);$("#mealDescription").value=m?.description||'';$("#mealNotes").value=m?.notes||'';makeRatings('#fatigueBeforePicker',m?.fatigueBefore||3);makeRatings('#fatigueAfterPicker',m?.fatigueAfter||3);photoData=m?.photoLocal||m?.photoUrl||null;photoRemoved=false;showPhotoPreview();$("#mealDialog").showModal()}
function showPhotoPreview(){const wrap=$("#photoPreviewWrap");wrap.hidden=!photoData;if(photoData)$("#photoPreview").src=photoData}
function openDay(){const d=ensureDay(db,selectedDate);$("#sleepHours").value=d.sleepHours??'';$("#activityType").value='';$("#activityMinutes").value='';$("#dayDialog").showModal()}
async function fileToDataUrl(file){if(!file)return null;const img=await createImageBitmap(file);const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.78)}
$("#mealPhoto").onchange=async e=>{photoData=await fileToDataUrl(e.target.files[0]);photoRemoved=false;showPhotoPreview()};$("#removePhoto").onclick=()=>{photoData=null;photoRemoved=true;showPhotoPreview()};
$("#mealForm").onsubmit=e=>{e.preventDefault();const d=ensureDay(db,selectedDate),id=$("#mealId").value,old=d.meals.find(x=>x.id===id);const meal=normalMeal({...old,id:id||uid(),date:selectedDate,type:$("#mealType").value,time:$("#mealTime").value,description:$("#mealDescription").value.trim(),fatigueBefore:Number($("#fatigueBeforePicker").dataset.value),fatigueAfter:Number($("#fatigueAfterPicker").dataset.value),notes:$("#mealNotes").value.trim(),photoLocal:photoData&&photoData.startsWith('data:')?photoData:(old?.photoLocal||null),photoUrl:photoRemoved?null:(old?.photoUrl||null),photoPath:photoRemoved?null:(old?.photoPath||null),updatedAt:new Date().toISOString()},selectedDate);if(old)Object.assign(old,meal);else d.meals.push(meal);setMealChanged(meal);$("#mealDialog").close();render()};
$("#dayForm").onsubmit=e=>{e.preventDefault();const d=ensureDay(db,selectedDate);d.sleepHours=$("#sleepHours").value===''?null:Number($("#sleepHours").value);const type=$("#activityType").value,min=Number($("#activityMinutes").value)||0;if(type&&min)d.activities.push({id:uid(),type,minutes:min,at:new Date().toISOString()});setDayChanged(selectedDate);$("#dayDialog").close();render()};
$("#copyYesterdayBreakfast").onclick=()=>{const dt=new Date(`${selectedDate}T12:00:00`);dt.setDate(dt.getDate()-1);const k=dt.toLocaleDateString('en-CA'),m=ensureDay(db,k).meals.find(x=>x.type==='Déjeuner');if(!m)return alert("Aucun déjeuner trouvé hier.");$("#mealType").value=m.type;$("#mealDescription").value=m.description;$("#mealNotes").value=m.notes||'';makeRatings('#fatigueBeforePicker',m.fatigueBefore||3);makeRatings('#fatigueAfterPicker',m.fatigueAfter||3)};
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$("#authForm").onsubmit=async e=>{e.preventDefault();if(!client)return;const email=$("#authEmail").value.trim(),msg=$("#authMessage");msg.textContent='Envoi en cours…';const redirectTo=`${location.origin}${location.pathname}`;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});msg.textContent=error?`Erreur : ${error.message}`:'Lien envoyé! Ouvre ton courriel sur cet appareil.'};
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`energie-repas-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#importFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text()),next=migrate(parsed);backup(db,'avant-import-v1.3');db=next;saveLocal('import');if(session&&confirm('Importer aussi cette copie dans Supabase?'))await seedCloudFromLocal();render()}catch(_){alert('Ce fichier JSON ne peut pas être importé.')}};
$("#themeToggle").onclick=()=>{db.settings.theme=db.settings.theme==='dark'?'system':'dark';saveLocal('theme');render()};$$('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;selectedDate=todayKey();render()});
window.addEventListener('online',()=>{updateSyncBadge();if(session)syncNow()});window.addEventListener('offline',updateSyncBadge);
async function initAuth(){if(!client){render();return}const {data}=await client.auth.getSession();session=data.session;client.auth.onAuthStateChange(async(event,newSession)=>{const firstLogin=!session&&!!newSession;session=newSession;updateSyncBadge();if(firstLogin){$("#authDialog").open&&$("#authDialog").close();await pullCloud(false);if(Object.values(db.days).some(d=>d.meals.length||d.water||d.sleepHours!=null)){const cloudHasData=Object.values(db.days).some(d=>d.meals.some(m=>m.photoPath)||false);if(!cloudHasData&&confirm('Veux-tu sauvegarder les données locales actuelles dans ton nouveau compte Supabase?'))await seedCloudFromLocal()}render()}});if(session){await pullCloud(false);await syncNow()}render()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
initAuth();
})();